import json, re

def main():
    """Generate code from lines.json"""

    with open("lines.json", "r", encoding="utf-8") as f:
        rules = json.load(f)

    if rules is None:
        return

    with open("lines.h", "w", encoding="utf-8") as f:
        f.write("// This file is generated by main.py. Do not edit manually.\n")
        f.write("#pragma once\n\n")
        f.write("#include \"line.h\"\n\n")
        f.write("void setupFormulas() {\n")
        f.write("    auto &L = Data::instance();\n\n")
        generate_code(rules, f)
        f.write("}\n")

def generate_code(rules, f):
    """Generate code from rules and write to file f"""

    pattern = r'\$(\d+)'
    for line in rules["lines"]:
        formula = "return 0;"
        deps = []

        line_id = re.sub(pattern, lambda m: f"{m.group(1)}", line["id"])

        if "formula" in line:
            formula = line["formula"]
            statement = re.sub(pattern, lambda m: f"L[{m.group(1)}]", formula)
            statement = f"{statement}"

            deps = re.findall(pattern, formula)
            deps = sorted(list(set(deps)))

        f.write(f"L.setFormula({line_id}, [&]() -> double {{ {statement} }}, {{{', '.join(deps)}}});\n")

if __name__ == "__main__":
    main()